[package]
name = "snake"
version = "0.1.0"
authors = ["ismdeep <ismdeep@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
piston_window = "*"
